### PR TITLE
Updated the example to the latest SvelteKit

### PR DESCRIPTION
**Pull request by ssbm-oro**
Hello, thanks again for creating this example which I used as a start for my project. I went ahead and updated the example to use the post-405 routing changes, and backported the refresh timeout logic. I also cleaned up some code based on some things I've learned in TypeScript since I started.

I tried to match your code styling and naming conventions with my additions. Let me know if you find any issues or have any questions!

### CODE REVIEW

**Comment by StrawHatHacker** [comment]
Thank you so much for the pull request. I'm still unfamiliar with the new major changes of sveltekit, but once I play with it a little bit, I will review this 👍

**Comment by StrawHatHacker** [comment]
@ssbm-oro 

When trying to run, I get: 
1.  500
The requested module '/@id/__x00__$env/static/public' does not provide an export named 'PUBLIC_DISCORD_OAUTH_CLIENT_ID'
SyntaxError: The requested module '/@id/__x00__$env/static/public' does not provide an export named 'PUBLIC_DISCORD_OAUTH_CLIENT_ID'.
Which can be fixed by moving `.env` to the root level.

2. Cannot find module '$env/static/public' or its corresponding type declarations.ts(2307).
In src/routes/dashboard/+page.svelte

3. Error in svelte.config.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'svelte-preprocess' imported from ...\SvelteKit-Discord-OAuth2\svelte.config.js.
In src/routes/dashboard/+page.svelte

**Comment by ssbm-oro** [comment]
1. I had my `.env` file in the root, I just must have not been thinking when I copied it to create the example file. That's been moved.

2. I wasn't having any trouble running it, but I was getting the compiler errors about not being able to find `$env/static/public` etc. It worked fine when I ran it so I ignored these. It wasn't an issue in my other project. I found that if I removed this line from `tsconfig.json`:
  `"include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"],`
  it does pick up the generated types automatically.
 
3. I didn't touch anything with `svelte-preprocess` or `svelte.config.js`. I'm not sure why you're getting an error.

**Comment by StrawHatHacker** [comment]
`import { env } from '$env/dynamic/public';` in `src/routes/api/v1/user/auth/+server.ts` returns an empty object

I fixed it by importing `PUBLIC_DISCORD_REDIRECT_URI` from `$env/static/public` and not from `$env/dynamic/public`.
Also, there was a wild `!` in line 22

**Comment by ssbm-oro** [comment]
Was `import { env } from '$env/dynamic/public';` an empty object in `+page.svelte`? It might just need to have the dev server run to generate the types for you.

`{ env }` gets its typing from `/src/app.d.ts`, which for me it's correctly picking up has a `PUBLIC_DISCORD_REDIRECT_URI` member.

image

**Comment by StrawHatHacker** [comment]
Restarted the server several times. If it's working as dynamic for both of us, let's leave it like this.

**Comment by StrawHatHacker** [comment]
@ssbm-oro 
In `src/routes/dashboard/+page.svelte` the `onMount` function never seems to get called and instead the `onDestroy` function gets called immediately. Tried testing those functions in different components, with the same results. Can you confirm you get the same behaviour?

**Comment by ssbm-oro** [comment]
`onMount` and `onDestory` are working as expected for me. Maybe try testing on a different browser and see if you get the same result?

**Comment by StrawHatHacker** [comment]
After updating to v427, redownloading `node_modules`, deleting `.svelte-kit` and running `npm update`, neither the `import { env } from '$env/dynamic/public';` nor the `onMount` and `onDestroy` work, in Firefox and Chrome.

Edit: Works in production, just not on the dev server

npm v8.18.0
Node.js v16.16.0

**Comment by StrawHatHacker** [comment]
Same issues in a different Windows machine with Node.js v16.17.0

Both env and mount problems, are working on Linux Mint 20.3, Kernel 5.15.9-46-generic, Node.js v16.17.0

**Comment by ssbm-oro** [comment]
https://github.com/sveltejs/kit/issues/5941#issuecomment-1221102524

Someone else is having the same issue with env on Windows, probably related.

edit to add: Reported as an issue here: https://github.com/sveltejs/kit/issues/6152#issue-1345915767

**Comment by StrawHatHacker** [comment]
Want to update to the latest SvelteKit version and see if it magically works?

**Comment by StrawHatHacker** [comment]
outdated

**Pull request closed without merging**
